### ISSUE TITLE
Couldn't load library tonclientjni

### ISSUE THREAD

**Issue by row2002** [mdorofeev/ton-client-kotlin#40]
Caused by: java.io.IOException: Couldn't load library library tonclientjni
	at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:141)
	at ee.nx01.tonclient.TonClient.<clinit>(TonClient.kt:132)
	... 75 more
Caused by: java.lang.UnsatisfiedLinkError: no tonclientjni in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:136)
	... 76 more

**Comment by row2002** [comment]
Ruuning on amd64 (ubuntu-22.04)
